# Generated by Django 5.2.6 on 2025-09-05 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GanjoorPoet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GanjoorCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('start_poem', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.ganjoorcat')),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.ganjoorpoet')),
            ],
        ),
        migrations.CreateModel(
            name='GanjoorFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GanjoorPoem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('has_comments', models.BooleanField(default=False)),
                ('gdb_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('highlight_text', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='core.ganjoorcat')),
                ('favorited_by', models.ManyToManyField(related_name='favorite_poems', through='core.GanjoorFavorite', to=settings.AUTH_USER_MODEL)),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='core.ganjoorpoet')),
            ],
        ),
        migrations.AddField(
            model_name='ganjoorfavorite',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ganjoorpoem'),
        ),
        migrations.CreateModel(
            name='GanjoorPoemAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='poem_audio/')),
                ('narrator', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='core.ganjoorpoem')),
            ],
        ),
        migrations.CreateModel(
            name='GanjoorVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('position', models.IntegerField(choices=[(0, 'Right (first hemistich)'), (1, 'Left (second hemistich)'), (2, 'Centered verse part 1'), (3, 'Centered verse part 2'), (4, 'Single line'), (5, 'Comment'), (-1, 'Paragraph')], default=0)),
                ('text', models.TextField()),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='core.ganjoorpoem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_mode', models.CharField(default='centered', max_length=50)),
                ('font_size', models.FloatField(default=16)),
                ('show_line_numbers', models.BooleanField(default=True)),
                ('last_highlight', models.CharField(blank=True, max_length=255, null=True)),
                ('browse_button_visible', models.BooleanField(default=True)),
                ('comments_button_visible', models.BooleanField(default=True)),
                ('copy_button_visible', models.BooleanField(default=True)),
                ('print_button_visible', models.BooleanField(default=True)),
                ('home_button_visible', models.BooleanField(default=True)),
                ('random_button_visible', models.BooleanField(default=True)),
                ('editor_button_visible', models.BooleanField(default=True)),
                ('download_button_visible', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ganjoorfavorite',
            unique_together={('user', 'poem')},
        ),
    ]
