# Generated by Django 5.2.6 on 2025-09-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GanjoorPoet',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, verbose_name='نام شاعر')),
                ('bio', models.TextField(blank=True, db_column='description', verbose_name='زندگینامه یا توضیحات')),
            ],
            options={
                'verbose_name': 'Poet',
                'verbose_name_plural': 'Poets',
                'db_table': 'poet',
            },
        ),
        migrations.CreateModel(
            name='GanjoorCat',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('text', models.CharField(db_column='text', max_length=255, verbose_name='عنوان بخش')),
                ('url', models.URLField(db_column='url', max_length=500, verbose_name='نشانی بخش')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', help_text='بخش والد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.ganjoorcat')),
                ('poet', models.ForeignKey(db_column='poet_id', help_text='شاعر مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.ganjoorpoet')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'cat',
            },
        ),
        migrations.CreateModel(
            name='GanjoorPoem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='عنوان شعر')),
                ('url', models.URLField(db_column='url', max_length=500, verbose_name='نشانی شعر')),
                ('cat', models.ForeignKey(db_column='cat_id', help_text='بخشی که شعر به آن تعلق دارد', on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='core.ganjoorcat')),
            ],
            options={
                'verbose_name': 'Poem',
                'verbose_name_plural': 'Poems',
                'db_table': 'poem',
            },
        ),
        migrations.CreateModel(
            name='GanjoorVerse',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('vorder', models.PositiveIntegerField(db_column='vorder', verbose_name='ترتیب مصرع')),
                ('position', models.IntegerField(choices=[(0, 'Right (مصرع اول)'), (1, 'Left (مصرع دوم)'), (2, 'Centered Verse 1 (مصرع اول/تنها)'), (3, 'Centered Verse 2 (مصرع دوم)'), (4, 'Single (مصرع آزاد/نیمایی)'), (5, 'Comment (توضیح)'), (-1, 'Paragraph (نثر)')], db_column='position', verbose_name='نوع و جایگاه مصرع')),
                ('text', models.TextField(db_column='text', verbose_name='متن مصرع')),
                ('poem', models.ForeignKey(db_column='poem_id', help_text='شعر مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='core.ganjoorpoem')),
            ],
            options={
                'verbose_name': 'Verse',
                'verbose_name_plural': 'Verses',
                'db_table': 'verse',
                'unique_together': {('poem', 'vorder')},
            },
        ),
    ]
