# Generated by Django 5.2.6 on 2025-09-07 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GanjoorPoet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Poet',
                'verbose_name_plural': 'Poets',
                'db_table': 'ganjoor_poet',
            },
        ),
        migrations.CreateModel(
            name='GanjoorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.ganjoorcategory')),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.ganjoorpoet')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'ganjoor_category',
            },
        ),
        migrations.CreateModel(
            name='GanjoorPoem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='core.ganjoorcategory')),
            ],
            options={
                'verbose_name': 'Poem',
                'verbose_name_plural': 'Poems',
                'db_table': 'ganjoor_poem',
            },
        ),
        migrations.CreateModel(
            name='GanjoorPoemAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='poem_audios/')),
                ('description', models.TextField(blank=True)),
                ('download_url', models.URLField(max_length=500)),
                ('is_direct', models.BooleanField(default=False)),
                ('sync_guid', models.CharField(max_length=255)),
                ('file_checksum', models.CharField(max_length=255)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.ganjoorpoem')),
            ],
            options={
                'verbose_name': 'Poem Audio',
                'verbose_name_plural': 'Poem Audios',
                'db_table': 'ganjoor_poem_audio',
            },
        ),
        migrations.CreateModel(
            name='GanjoorAudioSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_order', models.PositiveIntegerField()),
                ('millisec', models.PositiveIntegerField()),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ganjoorpoem')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ganjoorpoemaudio')),
            ],
            options={
                'verbose_name': 'Audio Sync',
                'verbose_name_plural': 'Audio Syncs',
                'db_table': 'ganjoor_audio_sync',
            },
        ),
        migrations.CreateModel(
            name='GanjoorVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of the verse in the poem')),
                ('text', models.TextField()),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='core.ganjoorpoem')),
            ],
            options={
                'db_table': 'ganjoor_verse',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GanjoorFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganjoor_favorites', to=settings.AUTH_USER_MODEL)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ganjoorpoem')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ganjoorverse')),
            ],
            options={
                'db_table': 'ganjoor_favorite',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_mode', models.CharField(default='centered', max_length=50)),
                ('font_size', models.FloatField(default=16)),
                ('show_line_numbers', models.BooleanField(default=True)),
                ('last_highlight', models.CharField(blank=True, max_length=255, null=True)),
                ('browse_button_visible', models.BooleanField(default=True)),
                ('comments_button_visible', models.BooleanField(default=True)),
                ('copy_button_visible', models.BooleanField(default=True)),
                ('print_button_visible', models.BooleanField(default=True)),
                ('home_button_visible', models.BooleanField(default=True)),
                ('random_button_visible', models.BooleanField(default=True)),
                ('editor_button_visible', models.BooleanField(default=True)),
                ('download_button_visible', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ganjoor_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.AddConstraint(
            model_name='ganjoorverse',
            constraint=models.UniqueConstraint(fields=('order', 'poem'), name='unique_verse_per_poem'),
        ),
        migrations.AddConstraint(
            model_name='ganjoorfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'poem'), name='unique_user_poem_fav'),
        ),
    ]
