# Generated by Django 5.2.6 on 2025-09-07 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ganjoorverse_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ganjoorfavorite',
            name='unique_user_poem_fav',
        ),
        migrations.AlterField(
            model_name='ganjooraudiosync',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='core.ganjoorpoemaudio'),
        ),
        migrations.AlterField(
            model_name='ganjooraudiosync',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_syncs', to='core.ganjoorpoem'),
        ),
        migrations.AlterField(
            model_name='ganjoorcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ganjoorfavorite',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.ganjoorpoem'),
        ),
        migrations.AlterField(
            model_name='ganjoorfavorite',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.ganjoorverse'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoem',
            name='url',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='sync_guid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ganjoorverse',
            name='order',
            field=models.PositiveIntegerField(db_index=True, help_text='Order of the verse in the poem'),
        ),
        migrations.AlterField(
            model_name='ganjoorverse',
            name='position',
            field=models.SmallIntegerField(choices=[(0, 'Right (مصرع اول)'), (1, 'Left (مصرع دوم)'), (2, 'Centered Verse 1 (ترجیع/ترکیب)'), (3, 'Centered Verse 2 (ترجیع/ترکیب)'), (4, 'Single (نیمایی/آزاد)'), (5, 'Comment (توضیح)'), (-1, 'Paragraph (نثر)')], default=0),
        ),
        migrations.AddConstraint(
            model_name='ganjoorfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'poem', 'verse'), name='unique_user_poem_verse_fav'),
        ),
    ]
