# Generated by Django 5.2.6 on 2025-09-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ganjoorfavorite_unique_user_poem_fav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganjoorpoet',
            name='century',
            field=models.CharField(choices=[('ancient', 'باستانی'), ('classical', 'کلاسیک'), ('contemporary', 'معاصر'), ('modern', 'نو')], db_index=True, default='classical', max_length=20),
        ),
    ]
