# Generated by Django 5.2.6 on 2025-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ganjoorpoet_century'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganjoorpoet',
            name='image',
            field=models.ImageField(blank=True, help_text='Portrait image of the poet', null=True, upload_to='poets/'),
        ),
    ]
