# Generated by Django 5.2.6 on 2025-09-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ganjoorpoet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganjoorpoet',
            name='image_slug',
            field=models.CharField(blank=True, help_text='English transliteration for image filename', max_length=255, null=True),
        ),
    ]
