# Generated by Django 5.2.6 on 2025-10-19 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ganjoorpoet_image_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ganjoorfavorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterField(
            model_name='ganjooraudiosync',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='core.ganjoorpoemaudio', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='ganjooraudiosync',
            name='millisec',
            field=models.PositiveIntegerField(verbose_name='Milliseconds'),
        ),
        migrations.AlterField(
            model_name='ganjooraudiosync',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_syncs', to='core.ganjoorpoem', verbose_name='Poem'),
        ),
        migrations.AlterField(
            model_name='ganjooraudiosync',
            name='verse_order',
            field=models.PositiveIntegerField(verbose_name='Verse Order'),
        ),
        migrations.AlterField(
            model_name='ganjoorcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.ganjoorcategory', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='ganjoorcategory',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.ganjoorpoet', verbose_name='Poet'),
        ),
        migrations.AlterField(
            model_name='ganjoorcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ganjoorcategory',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='ganjoorfavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='ganjoorfavorite',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.ganjoorpoem', verbose_name='Poem'),
        ),
        migrations.AlterField(
            model_name='ganjoorfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganjoor_favorites', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='ganjoorfavorite',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.ganjoorverse', verbose_name='Verse'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='core.ganjoorcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoem',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoem',
            name='url',
            field=models.CharField(db_index=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='download_url',
            field=models.URLField(max_length=500, verbose_name='Download URL'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='file',
            field=models.FileField(upload_to='poem_audios/', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='file_checksum',
            field=models.CharField(max_length=255, verbose_name='File Checksum'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='is_direct',
            field=models.BooleanField(default=False, verbose_name='Is Direct'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='is_uploaded',
            field=models.BooleanField(default=False, verbose_name='Is Uploaded'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.ganjoorpoem', verbose_name='Poem'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoemaudio',
            name='sync_guid',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Sync GUID'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoet',
            name='century',
            field=models.CharField(choices=[('ancient', 'Ancient'), ('classical', 'Classical'), ('contemporary', 'Contemporary'), ('modern', 'Modern')], db_index=True, default='classical', max_length=20, verbose_name='Century'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoet',
            name='image',
            field=models.ImageField(blank=True, help_text='Portrait image of the poet', null=True, upload_to='poets/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoet',
            name='image_slug',
            field=models.CharField(blank=True, help_text='English transliteration for image filename', max_length=255, null=True, verbose_name='Image Slug'),
        ),
        migrations.AlterField(
            model_name='ganjoorpoet',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ganjoorverse',
            name='order',
            field=models.PositiveIntegerField(db_index=True, help_text='Order of the verse in the poem', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='ganjoorverse',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='core.ganjoorpoem', verbose_name='Poem'),
        ),
        migrations.AlterField(
            model_name='ganjoorverse',
            name='position',
            field=models.SmallIntegerField(choices=[(0, 'Right (First Hemistich)'), (1, 'Left (Second Hemistich)'), (2, 'Centered Verse 1'), (3, 'Centered Verse 2'), (4, 'Single (Free Verse)'), (5, 'Comment'), (-1, 'Paragraph (Prose)')], default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='ganjoorverse',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='browse_button_visible',
            field=models.BooleanField(default=True, verbose_name='Browse Button Visible'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='comments_button_visible',
            field=models.BooleanField(default=True, verbose_name='Comments Button Visible'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='copy_button_visible',
            field=models.BooleanField(default=True, verbose_name='Copy Button Visible'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='download_button_visible',
            field=models.BooleanField(default=True, verbose_name='Download Button Visible'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='editor_button_visible',
            field=models.BooleanField(default=True, verbose_name='Editor Button Visible'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='font_size',
            field=models.FloatField(default=16, verbose_name='Font Size'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='home_button_visible',
            field=models.BooleanField(default=True, verbose_name='Home Button Visible'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='last_highlight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Highlight'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='print_button_visible',
            field=models.BooleanField(default=True, verbose_name='Print Button Visible'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='random_button_visible',
            field=models.BooleanField(default=True, verbose_name='Random Button Visible'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='show_line_numbers',
            field=models.BooleanField(default=True, verbose_name='Show Line Numbers'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ganjoor_settings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='view_mode',
            field=models.CharField(default='centered', max_length=50, verbose_name='View Mode'),
        ),
    ]
